<?php
/**
 *	Opening Hours
 */

namespace OpeningHours;

use OpeningHours\Module\AbstractModule;
use OpeningHours\Module as Module;

class OpeningHours extends AbstractModule {

	/**
	 *	Modules
	 *
	 *	@access 		protected
	 *	@type 			array
	 */
	protected $modules 	= array();

	/**
	 *	Constants
	 */
	const VERSION    = '2.0';
	const PREFIX     = 'op_';
	const DEBUG_MODE = false;

	/**
	 * 	Constructor
	 *
	 *	@access 		protected
	 */
	protected function __construct() {
		$this->registerHookCallbacks();

		$this->modules = array(
			'OpeningHours'				=> Module\OpeningHours::getInstance(),
			'I18n'								=> Module\I18n::getInstance(),
			'Ajax'								=> Module\Ajax::getInstance(),
			'CustomPostType\Set'	=> Module\CustomPostType\Set::getInstance()
		);
	}

	/**
	 *	Register callbacks for actions and filters
	 *
	 *	@access 		public
	 */
	public function registerHookCallbacks() {
		add_action( 'wp_enqueue_scripts',    __CLASS__ . '::loadResources' );
		add_action( 'admin_enqueue_scripts', __CLASS__ . '::loadResources' );
	}


	/**
	 *	Enqueues CSS, JavaScript, etc
	 *
	 * 	@access 			public
	 *	@static
	 *	@wp_action 		wp_enqueue_scripts, admin_enqueue_scripts
	 */
	public static function loadResources() {
		wp_register_script(
			self::PREFIX . 'js-backend',
			plugins_url( 'javascript/opening-hours-backend.js', dirname( __FILE__ ) ),
			array( 'jquery' ),
			self::VERSION,
			true
		);

		wp_register_style(
			self::PREFIX . 'admin',
			plugins_url( 'css/opening-hours-backend.css', dirname( __FILE__ ) ),
			array(),
			self::VERSION,
			'all'
		);

		if ( is_admin() ) {
			// Backend Styles and Scripts
			wp_enqueue_style( self::PREFIX . 'css-backend' );
			wp_enqueue_script( self::PREFIX . 'js-backend' );
		} else {
			// Frontend Styles and Scripts
		}
	}

	/**
	 * Clears caches of content generated by caching plugins like WP Super Cache
	 *
	 * @mvc Model
	 */
	protected static function clearCachingPlugins() {
		// WP Super Cache
		if ( function_exists( 'wp_cache_clear_cache' ) ) {
			wp_cache_clear_cache();
		}

		// W3 Total Cache
		if ( class_exists( 'W3_Plugin_TotalCacheAdmin' ) ) {
			$w3_total_cache = w3_instance( 'W3_Plugin_TotalCacheAdmin' );

			if ( method_exists( $w3_total_cache, 'flush_all' ) ) {
				$w3_total_cache->flush_all();
			}
		}
	}

}
