name: CI

on: [push]

jobs:
  php-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3]

    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v2
    - name: Composer Install
      uses: php-actions/composer@v5
    - name: Unit Test ✅
      uses: php-actions/phpunit@v2
      with:
        version: 4.8
        php_version: ${{ matrix.php }}
        configuration: phpunit.xml
